---
abstract: 'docs for all plugins in one document for easy reference'
author:
  - "Zoffix <'zoffix@cpan.org'>"
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-ZofCMS-PluginReference
provides:
  App::ZofCMS::PluginReference:
    file: lib/App/ZofCMS/PluginReference.pm
    version: 0.0107
resources:
  license: http://dev.perl.org/licenses/
version: 0.0107
